/* KPI encyclopedia. b = indicative range only, never a target. */
window.KPIS = [
/* ---------- ACQUISITION ---------- */
{n:"Unique visitors",c:"Acquisition",f:"Distinct devices or users in period",b:"—",fs:"Session count by distinct user; reconcile against their analytics to size the consent/blocking gap"},
{n:"Landing page conversion rate",c:"Acquisition",f:"Registrations started ÷ landing sessions",b:"3–12%",fs:"Funnel step 1; segment by affiliate, campaign, device"},
{n:"Registration start rate",c:"Acquisition",f:"Registration Started ÷ sessions",b:"4–15%",fs:"<code>Registration Started</code> with <code>entryPoint</code>"},
{n:"Cost per acquisition (CPA)",c:"Acquisition",f:"Marketing spend ÷ first-time depositors",b:"£100–£400+ in competitive regulated markets",fs:"Not captured — supplied by the client; used to price opportunities"},
{n:"Reg-to-FTD conversion",c:"Acquisition",f:"First-time depositors ÷ registrations",b:"35–65%",fs:"User-scope funnel Registration Completed → Deposit Outcome = success"},
{n:"Click-to-registration rate",c:"Acquisition",f:"Registration Started ÷ affiliate clicks",b:"5–20%",fs:"Requires <code>affiliateId</code> as a session property on entry"},
{n:"Traffic quality index by source",c:"Acquisition",f:"Composite of engagement depth and FTD rate by source",b:"Relative",fs:"Segment comparison across <code>affiliateId</code>; use engagement depth, not just conversion"},
{n:"Bounce / single-page-session rate",c:"Acquisition",f:"Sessions with one page view ÷ sessions",b:"25–55%",fs:"Session segment with page-view count = 1"},
{n:"Offer match rate",c:"Acquisition",f:"Sessions where the landing offer matches the referring offer",b:"Aim 100%",fs:"Capture <code>offerShown</code> on landing and compare against <code>campaignId</code>"},
{n:"Share of mobile traffic",c:"Acquisition",f:"Mobile sessions ÷ all sessions",b:"60–85%",fs:"Session property <code>deviceType</code>"},
{n:"App install-to-registration",c:"Acquisition",f:"Registrations ÷ installs",b:"25–50%",fs:"Mobile SDK first-open event through to Registration Completed"},
{n:"Return-visitor share",c:"Acquisition",f:"Sessions from known users ÷ all sessions",b:"40–70%",fs:"Sessions with an identity attached versus anonymous"},

/* ---------- REGISTRATION & KYC ---------- */
{n:"Registration completion rate",c:"Registration & KYC",f:"Registration Completed ÷ Registration Started",b:"40–65%",fs:"Funnel over <code>Registration Step Completed</code>"},
{n:"Step-level drop-off",c:"Registration & KYC",f:"1 − (step n+1 ÷ step n)",b:"Any step >25% needs investigation",fs:"Funnel with <code>stepNumber</code>; overlay device"},
{n:"Time to complete registration",c:"Registration & KYC",f:"Median seconds start → complete",b:"90–240s",fs:"<code>totalSeconds</code> on Registration Completed"},
{n:"Field-level abandonment",c:"Registration & KYC",f:"Abandonments attributed to the last engaged field",b:"Relative",fs:"Autocaptured form interaction plus <code>Registration Failed</code> with <code>fieldName</code>"},
{n:"Validation error rate per field",c:"Registration & KYC",f:"Validation errors ÷ field engagements",b:"<10% healthy",fs:"<code>validationErrors</code> property per step"},
{n:"KYC auto-pass rate",c:"Registration & KYC",f:"Automatically verified ÷ KYC started",b:"70–90%",fs:"<code>KYC Outcome</code> with <code>outcome</code> and <code>vendor</code>"},
{n:"KYC manual-review rate",c:"Registration & KYC",f:"Referred to manual ÷ KYC started",b:"10–30%",fs:"Outcome = referred; correlate with subsequent abandonment"},
{n:"Document upload success rate",c:"Registration & KYC",f:"Accepted uploads ÷ upload attempts",b:"60–85%",fs:"<code>KYC Document Uploaded</code> with <code>fileRejected</code> and <code>attemptNumber</code>"},
{n:"Time to verification",c:"Registration & KYC",f:"Median seconds KYC Started → Outcome",b:"Auto <30s; manual hours to days",fs:"<code>secondsToOutcome</code>"},
{n:"KYC abandonment rate",c:"Registration & KYC",f:"Started KYC, never completed ÷ started",b:"15–40%",fs:"User segment: KYC Started AND NOT Outcome = passed"},
{n:"Verified-to-deposit rate",c:"Registration & KYC",f:"Deposited ÷ verified",b:"50–75%",fs:"User funnel KYC passed → Deposit success"},
{n:"Affordability prompt completion",c:"Registration & KYC",f:"Completed ÷ prompted",b:"Market-specific",fs:"Instrument prompt shown and outcome — optimise for clarity, never for completion"},
{n:"Geolocation success rate (US)",c:"Registration & KYC",f:"Passes ÷ attempts",b:"85–97%",fs:"Custom Geolocation Attempt/Outcome events with reason and retry count"},

/* ---------- PAYMENTS ---------- */
{n:"Deposit success rate",c:"Payments",f:"Successful deposits ÷ deposit attempts",b:"75–92% overall; card lower than wallets",fs:"<code>Deposit Outcome</code>; always segment by method and provider"},
{n:"First deposit success rate",c:"Payments",f:"Successful ÷ attempted, first deposit only",b:"5–15 points below returning players",fs:"Filter <code>isFirstDeposit</code> = true"},
{n:"Attempts per successful deposit",c:"Payments",f:"Deposit Attempted ÷ Deposit Outcome success",b:"1.1–1.4",fs:"Above 1.5 indicates serious cashier friction"},
{n:"Decline rate by reason",c:"Payments",f:"Declines of reason R ÷ all attempts",b:"Relative",fs:"<code>declineReason</code> and <code>providerCode</code> — audit the message shown for each"},
{n:"Issuer decline rate",c:"Payments",f:"Issuer-declined ÷ card attempts",b:"8–25% (gambling MCC is structurally high)",fs:"Provider code mapping; not fixable on site — the recovery path is"},
{n:"3DS challenge rate",c:"Payments",f:"Challenged ÷ card attempts",b:"20–60% in Europe",fs:"<code>threeDsUsed</code>"},
{n:"3DS completion rate",c:"Payments",f:"Completed ÷ challenged",b:"70–90%",fs:"<code>threeDsOutcome</code>; watch abandonment inside the challenge"},
{n:"Retry rate after decline",c:"Payments",f:"Retried ÷ declined",b:"40–70%",fs:"Sequence: failed outcome THEN another attempt within the session"},
{n:"Retry success rate",c:"Payments",f:"Successful retries ÷ retries",b:"30–60%",fs:"Measures whether the error message actually helps"},
{n:"Time to deposit",c:"Payments",f:"Median seconds Cashier Opened → success",b:"45–120s",fs:"<code>secondsElapsed</code>; compare saved vs new method"},
{n:"Saved-method adoption",c:"Payments",f:"Deposits using a saved method ÷ deposits",b:"40–70% for returning players",fs:"<code>isSavedMethod</code>"},
{n:"Payment method mix",c:"Payments",f:"Share of deposits by method",b:"Market-specific",fs:"<code>paymentMethod</code> on Deposit Outcome"},
{n:"Average deposit value",c:"Payments",f:"Total deposits ÷ deposit count",b:"Client-specific",fs:"Use bucketed distribution in Fullstory; exact value from the warehouse"},
{n:"Cashier abandonment rate",c:"Payments",f:"Cashier Opened with no attempt ÷ Cashier Opened",b:"15–35%",fs:"Segment: Cashier Opened AND NOT Deposit Attempted"},
{n:"Withdrawal completion rate",c:"Payments",f:"Withdrawal Requested ÷ Withdrawal Started",b:"70–90%",fs:"Funnel; capture <code>blockReason</code> on failure"},
{n:"Withdrawal processing time",c:"Payments",f:"Request → funds sent",b:"Instant to 5 days by method",fs:"Server-side event via the Events API; browser cannot know this"},
{n:"Reverse-withdrawal rate",c:"Payments",f:"Cancelled withdrawals ÷ requests",b:"Watch closely — an RG and fairness concern",fs:"Instrument cancellation; a high rate with prominent cancel UI is a design question"},
{n:"Chargeback rate",c:"Payments",f:"Chargebacks ÷ card deposits",b:"<0.5% target",fs:"Client's data; correlate with Fullstory sessions to find the confusion driving disputes"},
{n:"Payment error rate",c:"Payments",f:"Technical errors ÷ attempts",b:"<2%",fs:"JS and network errors during the cashier flow"},

/* ---------- CASINO ---------- */
{n:"Games per session",c:"Casino",f:"Distinct games launched ÷ session",b:"1.5–4",fs:"<code>Game Launched</code> distinct count"},
{n:"Game launch success rate",c:"Casino",f:"Load success ÷ launches",b:"95–99.5%",fs:"<code>Game Load Outcome</code> by provider and device"},
{n:"Time to playable",c:"Casino",f:"Median seconds launch → ready",b:"2–6s",fs:"<code>secondsToLoad</code>"},
{n:"Lobby-to-launch conversion",c:"Casino",f:"Sessions launching a game ÷ lobby sessions",b:"45–70%",fs:"Funnel Lobby Viewed → Game Launched"},
{n:"Tile click-through by position",c:"Casino",f:"Clicks ÷ impressions at position P",b:"Steep decay after row 2",fs:"<code>lobbyPosition</code>; normalise before ranking games"},
{n:"Lobby scroll depth",c:"Casino",f:"Median proportion of the grid reached",b:"Often <30%",fs:"Autocaptured scroll data on lobby pages"},
{n:"Search usage rate",c:"Casino",f:"Sessions using search ÷ lobby sessions",b:"10–30%",fs:"<code>Lobby Search</code>"},
{n:"Zero-result search rate",c:"Casino",f:"Zero-result searches ÷ searches",b:"<10% healthy",fs:"<code>hadZeroResults</code>; the top zero-result queries are the deliverable"},
{n:"Search-to-launch rate",c:"Casino",f:"Launches after search ÷ searches",b:"50–75%",fs:"Sequence: Lobby Search THEN Game Launched"},
{n:"Demo-to-real conversion",c:"Casino",f:"Real-money play after demo ÷ demo players",b:"5–20%",fs:"<code>isDemo</code> on Game Launched; user-scope sequence"},
{n:"Spins per session",c:"Casino",f:"Spin count ÷ session",b:"Client-specific",fs:"Not capturable inside the canvas — obtain from the platform and join by session"},
{n:"Session length (casino)",c:"Casino",f:"Median active minutes",b:"15–60 min",fs:"Fullstory session duration; beware idle-tab contamination"},
{n:"Game abandonment within 60s",c:"Casino",f:"Exits under 60s ÷ launches",b:"15–35%",fs:"<code>secondsInGame</code> on Game Exited — a strong proxy for load or expectation failure"},
{n:"Live dealer join rate",c:"Casino",f:"Tables joined ÷ live lobby views",b:"20–45%",fs:"<code>Live Dealer Table Joined</code> with <code>secondsWaiting</code>"},
{n:"Jackpot banner engagement",c:"Casino",f:"Clicks ÷ impressions",b:"1–6%",fs:"<code>Jackpot Banner Interaction</code>; check for dead clicks on decorative versions"},
{n:"RTP display compliance",c:"Casino",f:"Sessions where RTP information was displayed",b:"Market-mandated",fs:"Viewport-visibility event — evidence for compliance, not DOM presence"},
{n:"Provider mix by revenue",c:"Casino",f:"Share of play by game provider",b:"Client-specific",fs:"<code>provider</code> on launch events; cross-reference with failure rates"},

/* ---------- SPORTSBOOK ---------- */
{n:"Betslip conversion rate",c:"Sportsbook",f:"Bet Placed ÷ Selection Added",b:"35–65%",fs:"Funnel; split in-play and pre-match"},
{n:"Bet acceptance rate",c:"Sportsbook",f:"Accepted ÷ placed",b:"92–99%",fs:"<code>Bet Outcome</code> with <code>rejectionReason</code>"},
{n:"Price-change rejection rate",c:"Sportsbook",f:"Rejected for odds change ÷ placed",b:"1–8%, far higher in-play",fs:"<code>Odds Changed In Betslip</code> plus rejection outcome"},
{n:"Time in betslip",c:"Sportsbook",f:"Median seconds first selection → placement",b:"15–60s",fs:"<code>secondsInBetslip</code>; long dwell raises rejection risk"},
{n:"In-play share of turnover",c:"Sportsbook",f:"In-play stakes ÷ total stakes",b:"50–75% mature markets",fs:"<code>isInPlay</code>; instrument separately throughout"},
{n:"Multiples attach rate",c:"Sportsbook",f:"Multi-leg bets ÷ bets",b:"30–60%",fs:"<code>legCount</code> > 1 on Bet Placed"},
{n:"Average legs per multiple",c:"Sportsbook",f:"Total legs ÷ multiple bets",b:"3–6",fs:"<code>legCount</code> distribution"},
{n:"Bet builder adoption",c:"Sportsbook",f:"Bet builder bets ÷ bets",b:"10–35% and rising",fs:"<code>Bet Builder Interaction</code> through to placement"},
{n:"Cash-out usage rate",c:"Sportsbook",f:"Cash-outs taken ÷ eligible open bets",b:"15–40%",fs:"<code>Cash Out Viewed / Taken</code>"},
{n:"Cash-out offer decline rate",c:"Sportsbook",f:"Viewed but not taken ÷ viewed",b:"Relative",fs:"Watch for value changing mid-decision — a major trust issue"},
{n:"Navigation depth to selection",c:"Sportsbook",f:"Median clicks landing → selection added",b:"3–6",fs:"Journey analysis from entry to Selection Added"},
{n:"Quick-stake usage",c:"Sportsbook",f:"Bets using preset stake ÷ bets",b:"40–70% on mobile",fs:"<code>usedQuickStake</code> on Stake Entered"},
{n:"In-play stream start rate",c:"Sportsbook",f:"Streams started ÷ eligible views",b:"Client-specific",fs:"<code>In-Play Stream Started</code> with <code>secondsToStart</code> and <code>failed</code>"},
{n:"Hold percentage",c:"Sportsbook",f:"GGR ÷ handle",b:"5–10%",fs:"Not a Fullstory metric — from the warehouse; used to value opportunities"},
{n:"Bets per active",c:"Sportsbook",f:"Bets ÷ active players",b:"Client-specific",fs:"Warehouse; correlate with Fullstory engagement segments"},
{n:"Suspended-market interaction rate",c:"Sportsbook",f:"Interactions with suspended markets ÷ interactions",b:"Minimise",fs:"Error clicks on suspended selections — a common and fixable frustration"},

/* ---------- POKER & BINGO ---------- */
{n:"Client download completion",c:"Poker & Bingo",f:"Installs ÷ download starts",b:"50–80%",fs:"Instrument download initiation; installation itself is outside the browser"},
{n:"Seat-fill time",c:"Poker & Bingo",f:"Median seconds to be seated",b:"Under 30s ideal",fs:"Custom Table Joined event with wait duration"},
{n:"Tournament registration completion",c:"Poker & Bingo",f:"Registered ÷ registration started",b:"70–90%",fs:"Custom funnel; watch buy-in confirmation friction"},
{n:"Hands per hour",c:"Poker & Bingo",f:"Hands dealt ÷ table hours",b:"60–100 online",fs:"Platform data — join by session"},
{n:"Rake per active",c:"Poker & Bingo",f:"Rake ÷ active players",b:"Client-specific",fs:"Warehouse"},
{n:"Table liquidity",c:"Poker & Bingo",f:"Occupied seats ÷ available seats",b:"Critical below ~40%",fs:"Platform data; instrument the lobby experience when liquidity is low"},
{n:"Bingo tickets per player",c:"Poker & Bingo",f:"Tickets purchased ÷ players in room",b:"Client-specific",fs:"Custom ticket purchase events"},
{n:"Chat engagement rate",c:"Poker & Bingo",f:"Players using chat ÷ players in room",b:"20–50% (bingo is social)",fs:"Interaction events only — never the message content"},

/* ---------- SOCIAL GAMING ---------- */
{n:"DAU / MAU stickiness",c:"Social Gaming",f:"Daily actives ÷ monthly actives",b:"15–30%",fs:"User segments by activity window"},
{n:"ARPDAU",c:"Social Gaming",f:"Revenue ÷ daily active users",b:"$0.05–$0.50",fs:"IAP and ad events joined to active-user counts"},
{n:"Payer conversion rate",c:"Social Gaming",f:"Paying users ÷ active users",b:"1–5%",fs:"User segment with IAP Completed"},
{n:"ARPPU",c:"Social Gaming",f:"Revenue ÷ paying users",b:"$10–$80 monthly",fs:"<code>priceTier</code> on IAP Completed"},
{n:"D1 retention",c:"Social Gaming",f:"Returned next day ÷ installs",b:"25–45%",fs:"User-scope return analysis"},
{n:"D7 retention",c:"Social Gaming",f:"Returned day 7 ÷ installs",b:"10–20%",fs:"User-scope return analysis"},
{n:"D30 retention",c:"Social Gaming",f:"Returned day 30 ÷ installs",b:"3–10%",fs:"User-scope return analysis"},
{n:"Tutorial completion rate",c:"Social Gaming",f:"Completed ÷ started",b:"60–85%",fs:"<code>Tutorial Step Completed</code> funnel with skip rate"},
{n:"Level churn point",c:"Social Gaming",f:"Level with the highest abandonment",b:"Find it, then tune it",fs:"<code>Level Failed</code> by <code>levelNumber</code> and <code>attemptNumber</code>"},
{n:"Store open rate",c:"Social Gaming",f:"Store Opened ÷ sessions",b:"10–30%",fs:"<code>Store Opened</code> with <code>trigger</code>"},
{n:"IAP funnel conversion",c:"Social Gaming",f:"IAP Completed ÷ IAP Initiated",b:"60–85%",fs:"Funnel; failures are often platform payment sheet issues"},
{n:"Rewarded ad completion",c:"Social Gaming",f:"Watched to completion ÷ offered",b:"60–85%",fs:"<code>Rewarded Ad Offered / Watched</code>"},
{n:"Ad ARPDAU",c:"Social Gaming",f:"Ad revenue ÷ daily actives",b:"$0.02–$0.20",fs:"Ad events joined to revenue data"},
{n:"Session length (social)",c:"Social Gaming",f:"Median minutes per session",b:"5–20 min",fs:"Fullstory session duration"},
{n:"Sessions per day",c:"Social Gaming",f:"Sessions ÷ daily active users",b:"2–6",fs:"Session counts per user per day"},
{n:"Daily reward streak retention",c:"Social Gaming",f:"Players maintaining a streak",b:"Client-specific",fs:"<code>Daily Reward Claimed</code> with <code>streakDay</code>"},

/* ---------- RETENTION & VALUE ---------- */
{n:"D1 / D7 / D30 return rate",c:"Retention & Value",f:"Returned within window ÷ new players",b:"D1 25–40%, D7 15–25%, D30 10–18%",fs:"User-scope return segments from registration date"},
{n:"Second-deposit rate",c:"Retention & Value",f:"Made a 2nd deposit ÷ first-time depositors",b:"40–65%",fs:"User segment with deposit success count ≥ 2"},
{n:"Time to second deposit",c:"Retention & Value",f:"Median days between 1st and 2nd",b:"2–10 days",fs:"User-scope sequence with timing"},
{n:"Monthly active players",c:"Retention & Value",f:"Players wagering in the month",b:"Client-specific",fs:"User segments on wagering events"},
{n:"Churn rate",c:"Retention & Value",f:"Players inactive N days ÷ prior actives",b:"30–60% at 90 days",fs:"User segment with no activity in window"},
{n:"Reactivation rate",c:"Retention & Value",f:"Returned lapsed players ÷ targeted lapsed",b:"5–20%",fs:"Segment lapsed users and measure return plus the landing experience"},
{n:"ARPU / NGR per active",c:"Retention & Value",f:"NGR ÷ active players",b:"Client-specific",fs:"Warehouse; the figure you should use to price every opportunity"},
{n:"Lifetime value",c:"Retention & Value",f:"Modelled NGR over 6–12 months",b:"Client-specific",fs:"Warehouse; join via Data Direct for behavioural cohorts"},
{n:"LTV : CAC ratio",c:"Retention & Value",f:"LTV ÷ acquisition cost",b:"3:1 healthy",fs:"Client figure; the frame for every business case you present"},
{n:"VIP revenue concentration",c:"Retention & Value",f:"NGR from top 1% ÷ total NGR",b:"30–50%",fs:"Segment by <code>accountTier</code>; always analyse separately"},
{n:"Cross-sell rate",c:"Retention & Value",f:"Dual-product players ÷ single-product players",b:"10–30%",fs:"User segments across both verticals; measure the second session, not the first"},
{n:"Bonus-to-deposit conversion",c:"Retention & Value",f:"Deposited after claiming ÷ claimants",b:"40–70%",fs:"Sequence: Bonus Claimed THEN Deposit success"},
{n:"Wagering completion rate",c:"Retention & Value",f:"Completed wagering ÷ bonuses claimed",b:"10–35%",fs:"Requires platform data; instrument the progress display and whether players see it"},
{n:"Bonus cost ratio",c:"Retention & Value",f:"Bonus cost ÷ GGR",b:"20–40%",fs:"Warehouse"},
{n:"Push opt-in rate",c:"Retention & Value",f:"Opted in ÷ prompted",b:"30–60%",fs:"Instrument prompt timing and outcome; timing is the lever"},
{n:"Email/SMS opt-in rate",c:"Retention & Value",f:"Opted in ÷ registrations",b:"40–75%",fs:"<code>marketingOptIn</code> on Registration Completed"},
{n:"Account closure rate",c:"Retention & Value",f:"Closures ÷ active accounts",b:"Monitor trend",fs:"<code>Account Closure Started</code> with <code>reasonSelected</code>"},

/* ---------- RESPONSIBLE GAMBLING ---------- */
{n:"RG tool adoption rate",c:"Responsible Gambling",f:"Players using any RG tool ÷ actives",b:"3–15%",fs:"<code>RG Tool Interaction</code>"},
{n:"Deposit limit setting rate",c:"Responsible Gambling",f:"Players setting a limit ÷ actives",b:"2–10%",fs:"Tool type = deposit limit, action = set"},
{n:"Limit-setting completion",c:"Responsible Gambling",f:"Completed ÷ started",b:"Aim high — friction here is a design failure",fs:"Funnel through the limit-setting flow"},
{n:"Reality check interaction rate",c:"Responsible Gambling",f:"Acknowledged ÷ displayed",b:"Market-mandated",fs:"Display evidence plus interaction"},
{n:"Time-out uptake",c:"Responsible Gambling",f:"Time-outs taken ÷ actives",b:"Low single digits",fs:"Tool type = time-out"},
{n:"Self-exclusion completion",c:"Responsible Gambling",f:"Completed ÷ started",b:"Must be near 100% — investigate any drop",fs:"Funnel; any friction here is a regulatory risk, audit it explicitly"},
{n:"RG tool discoverability",c:"Responsible Gambling",f:"Median clicks from any page to an RG tool",b:"Fewer is better",fs:"Journey analysis to RG pages"},
{n:"Mandated message display coverage",c:"Responsible Gambling",f:"Sessions where required messaging was visible ÷ eligible sessions",b:"Aim 100%",fs:"Viewport-visibility events — evidence, not DOM presence"},
{n:"Limit-increase request rate",c:"Responsible Gambling",f:"Increase requests ÷ limit holders",b:"Monitor",fs:"<code>limitChangeDirection</code>; cooling-off periods are usually mandated"},

/* ---------- TECHNICAL ---------- */
{n:"JavaScript error rate",c:"Technical",f:"Sessions with ≥1 error ÷ sessions",b:"<5% healthy",fs:"Autocaptured; group by signature and rank by sessions affected"},
{n:"Error click rate",c:"Technical",f:"Sessions with an error click ÷ sessions",b:"<2%",fs:"Derived signal — the highest-yield starting point on any new account"},
{n:"Page load time (LCP)",c:"Technical",f:"Largest Contentful Paint, 75th percentile",b:"<2.5s good",fs:"Autocaptured performance data by page group and device"},
{n:"Interaction responsiveness (INP)",c:"Technical",f:"Interaction to Next Paint, 75th percentile",b:"<200ms good",fs:"Performance data; critical on betslips and in-play"},
{n:"Cumulative Layout Shift",c:"Technical",f:"CLS, 75th percentile",b:"<0.1 good",fs:"Layout shifts on odds updates are a classic sportsbook problem"},
{n:"Time to first byte",c:"Technical",f:"TTFB",b:"<800ms",fs:"Performance data; segment by market and CDN edge"},
{n:"API failure rate",c:"Technical",f:"Failed requests ÷ requests",b:"<1%",fs:"Network data in replay; correlate with player-visible outcomes"},
{n:"App crash-free sessions",c:"Technical",f:"Sessions without a crash ÷ sessions",b:">99.5%",fs:"Mobile SDK, joined with crash reporting"},
{n:"Conversion by load-time band",c:"Technical",f:"Conversion within each load-time bucket",b:"Find the breakpoint",fs:"Segment by performance band and compare downstream conversion"},
{n:"Third-party script impact",c:"Technical",f:"Load-time contribution by script",b:"Audit quarterly",fs:"Network timing; gambling sites carry heavy tag loads"},

/* ---------- SUPPORT ---------- */
{n:"Contact rate per session",c:"Support",f:"Support contacts ÷ sessions",b:"0.5–3%",fs:"<code>Support Contact Initiated</code> with <code>pageContext</code>"},
{n:"Error-driven contact share",c:"Support",f:"Contacts preceded by an error ÷ contacts",b:"Relative",fs:"Sequence within 5 minutes — sizes the technical contribution to support cost"},
{n:"Cannot-reproduce close rate",c:"Support",f:"Tickets closed unreproduced ÷ tickets",b:"Drive toward zero",fs:"Replay links on tickets; measure before and after the integration"},
{n:"Average handle time",c:"Support",f:"Median minutes per ticket",b:"Client-specific",fs:"Support tool data; correlate with replay-link availability"},
{n:"Self-service deflection rate",c:"Support",f:"Help views not followed by a contact ÷ help views",b:"Relative",fs:"Sequence: help content viewed AND NOT contact within the session"},
{n:"Contact drivers by journey",c:"Support",f:"Ranked preceding paths before contact",b:"Top 5 = the fix list",fs:"Backward journey analysis from Support Contact Initiated"},

/* ---------- EXPERIENCE ---------- */
{n:"Frustration rate per session",c:"Experience",f:"Sessions with ≥1 frustration signal ÷ sessions",b:"5–20%",fs:"Derived signals; exclude known repeat-click controls first"},
{n:"Rage click rate",c:"Experience",f:"Sessions with a rage click ÷ sessions",b:"2–10%",fs:"Suppress on steppers, quick-stake chips and spin buttons or the data is worthless"},
{n:"Dead click rate",c:"Experience",f:"Sessions with a dead click ÷ sessions",b:"3–12%",fs:"Filter to elements styled as interactive before reporting"},
{n:"Thrashed cursor rate",c:"Experience",f:"Sessions with cursor thrashing ÷ sessions",b:"1–6%",fs:"Strong signal on search and lobby pages"},
{n:"Form abandonment rate",c:"Experience",f:"Forms engaged but not submitted ÷ engaged",b:"Form-specific",fs:"Autocaptured form interaction"},
{n:"Scroll depth",c:"Experience",f:"Median proportion of page reached",b:"Page-specific",fs:"Autocaptured; essential for lobby and promotion pages"},
{n:"Task success rate",c:"Experience",f:"Completed intended task ÷ attempted",b:"Define per task",fs:"Funnel per task; the cleanest UX metric you can give a design team"},
{n:"Net Promoter Score",c:"Experience",f:"Promoters % − detractors %",b:"Gambling typically low",fs:"Survey tool integration — join the response to the session"},
{n:"Customer effort score",c:"Experience",f:"Survey: how easy was that",b:"Higher is better",fs:"Survey integration; pair with the replay of that journey"},
{n:"Accessibility error rate",c:"Experience",f:"Pages with detectable a11y failures",b:"Audit separately",fs:"Not a Fullstory feature — but replay evidences keyboard and zoom journeys"}
];

/* ---------- GLOSSARY ---------- */
window.GLOSSARY = [
{t:"Autocapture",c:"fullstory",d:"Fullstory indexing every click, navigation, form interaction, error and performance timing without tagging, which allows retroactive analysis of questions nobody thought to ask."},
{t:"Data Direct",c:"fullstory",d:"Scheduled export of Fullstory event data into the client's own warehouse (Snowflake, BigQuery, Redshift, Databricks, S3) so behaviour can be joined to revenue."},
{t:"Dead click",c:"fullstory",d:"A click producing no DOM change and no navigation — something looked interactive and was not."},
{t:"Element blueprint / named element",c:"fullstory",d:"A stable identifier for an element, typically via <code>data-fs-element</code>, so it stays findable across locales and rebuilds."},
{t:"Error click",c:"fullstory",d:"A click immediately followed by a JavaScript error. The highest-yield frustration signal for finding real, fixable defects."},
{t:"fs-exclude",c:"fullstory",d:"CSS class preventing an element and its subtree from being captured at all."},
{t:"fs-mask",c:"fullstory",d:"CSS class replacing an element's text with placeholder characters while keeping layout intact."},
{t:"fs-unmask",c:"fullstory",d:"CSS class opting an element back into capture inside a masked ancestor."},
{t:"Funnel",c:"fullstory",d:"An ordered sequence of steps with step-to-step conversion, drop-off and timing, and direct access to the replays of those who dropped."},
{t:"Journey / path analysis",c:"fullstory",d:"The actual routes users take forward from a start point or backward from an endpoint, rather than a hypothesis you defined in advance."},
{t:"Namespace (_fs_namespace)",c:"fullstory",d:"The global variable the capture API attaches to, default <code>FS</code>. Rename when it collides with an existing global on the client's platform."},
{t:"Rage click",c:"fullstory",d:"Rapid repeated clicking in a small area. Genuine signal, but contaminated by steppers and quick-stake controls unless suppressed on those elements."},
{t:"Retroactive analysis",c:"fullstory",d:"Asking a new question of already-captured data because autocapture indexed everything, rather than needing to tag in advance."},
{t:"Segment",c:"fullstory",d:"A saved, re-evaluating definition of a set of sessions or users. The object funnels, dashboards, metrics and replay lists are built from."},
{t:"Session (Fullstory)",c:"fullstory",d:"A contiguous run of activity from one browser, closing after a period of inactivity and split when very long."},
{t:"setIdentity",c:"fullstory",d:"The API call binding a session to a stable user ID and setting user properties. The join that makes revenue analysis possible."},
{t:"Session scope vs user scope",c:"fullstory",d:"Whether a segment asks 'which visits had this shape' or 'which people ever did this'. Different questions, different numbers."},
{t:"Thrashed cursor",c:"fullstory",d:"Rapid erratic pointer movement, indicating confusion, searching or waiting."},
{t:"trackEvent",c:"fullstory",d:"The API call sending a named custom event with properties — how business-meaningful moments enter the dataset."},
{t:"Type suffix",c:"fullstory",d:"Legacy property naming convention encoding type: <code>_str</code>, <code>_int</code>, <code>_real</code>, <code>_bool</code>, <code>_date</code>, <code>_obj</code>, and pluralised forms for arrays."},
{t:"Watched element",c:"fullstory",d:"An element you have explicitly asked Fullstory to track engagement with, used for measuring exposure to specific components."},

{t:"Affordability check",c:"gambling",d:"Assessment of whether a player can sustain their losses. A significant mid-journey friction in the GB market — clarify it, never optimise it away."},
{t:"AML",c:"gambling",d:"Anti-money-laundering. Drives source-of-funds checks and hard stops that appear in your funnel as drop-offs but are legally required."},
{t:"ARPDAU",c:"gambling",d:"Average revenue per daily active user. The standard monetisation metric in social and free-to-play gaming."},
{t:"Bet builder",c:"gambling",d:"A sportsbook feature combining multiple selections within a single event into one bet. High-margin and fast-growing."},
{t:"Bonus abuse",c:"gambling",d:"Exploiting promotional terms systematically. Operators monitor it closely; it affects how freely bonuses can be offered."},
{t:"Cash out",c:"gambling",d:"Settling an open bet early for an offered value. Popular, and a frequent source of trust complaints when the value changes mid-decision."},
{t:"Churn",c:"gambling",d:"A defined period without activity, commonly 30, 60 or 90 days."},
{t:"Dormancy",c:"gambling",d:"A regulatory status for inactive accounts, with specific handling and communication rules."},
{t:"FTD",c:"gambling",d:"First Time Depositor. The core acquisition currency; affiliates are usually paid per FTD."},
{t:"GAMSTOP",c:"gambling",d:"The GB national multi-operator self-exclusion scheme. Licensed operators must integrate with it."},
{t:"Game weighting",c:"gambling",d:"How much different games contribute toward a bonus wagering requirement. Rarely communicated clearly and a common complaint driver."},
{t:"GGR",c:"gambling",d:"Gross Gaming Revenue — stakes minus player winnings, before costs."},
{t:"Handle / turnover",c:"gambling",d:"Total amount wagered. Not revenue; be alert when a client quotes it as though it were."},
{t:"Hold %",c:"gambling",d:"Sportsbook GGR as a share of handle — what the book actually kept. Typically 5–10%."},
{t:"House edge",c:"gambling",d:"The operator's theoretical long-run margin on a casino game: 100% minus RTP."},
{t:"In-play",c:"gambling",d:"Betting while an event is under way. Time-critical, latency-sensitive, and the majority of turnover in mature markets."},
{t:"KYC",c:"gambling",d:"Know Your Customer — identity, age and address verification. In Great Britain it must happen before deposit or play, placing it inside the conversion funnel."},
{t:"NGR",c:"gambling",d:"Net Gaming Revenue — GGR less bonuses, duty, payment fees and often affiliate commission. The number that matters commercially."},
{t:"Overround / vig",c:"gambling",d:"The theoretical margin built into a market's prices. A book priced to 105% carries a 5% overround."},
{t:"PAM",c:"gambling",d:"Player Account Management platform — the system of record for accounts, wallet, bonuses and compliance."},
{t:"PSP",c:"gambling",d:"Payment service provider. Operators run several and route between them; routing changes move your deposit success rate without any site change."},
{t:"Reality check",c:"gambling",d:"A periodic interruption showing elapsed time and net position. Mandated in several markets."},
{t:"Reverse withdrawal",c:"gambling",d:"Cancelling a pending withdrawal to return funds to the playable balance. Regulators scrutinise how prominently this is offered."},
{t:"RTP",c:"gambling",d:"Return to Player — the long-run percentage a casino game returns, typically 92–97%."},
{t:"Self-exclusion",c:"gambling",d:"A player blocking their own access, at operator or national scheme level. Absolute and non-negotiable."},
{t:"SoF / SoW",c:"gambling",d:"Source of funds / source of wealth. Evidence requirements triggered by thresholds or behaviour; never capture the documents."},
{t:"VIP",c:"gambling",d:"High-value players under manual account management. A small population carrying a very large share of revenue."},
{t:"Wagering requirement",c:"gambling",d:"How many times a bonus must be staked before withdrawal — '30x'. The largest single source of player confusion in the industry."},
{t:"White label",c:"gambling",d:"An operator running on another company's platform and licence. Determines which pages you can actually deploy code to."},

{t:"Consent management platform (CMP)",c:"data",d:"The system capturing and enforcing a visitor's cookie and tracking choices. Gates whether capture runs at all."},
{t:"Controller / processor",c:"data",d:"Under GDPR the operator is the controller and Fullstory the processor. Governs who is accountable for what."},
{t:"CSP",c:"data",d:"Content Security Policy — the browser rule set restricting which hosts can serve scripts and receive connections. Must be amended for capture to work."},
{t:"Data residency",c:"data",d:"Where data is physically stored. Often constrained by the operator's licence conditions."},
{t:"DPIA",c:"data",d:"Data Protection Impact Assessment — required for higher-risk processing. Behavioural analytics on gambling data usually warrants one."},
{t:"DSAR",c:"data",d:"Data Subject Access Request. The client needs a documented process for answering one that includes Fullstory data."},
{t:"First-party capture",c:"data",d:"Serving the capture script from the client's own subdomain to reduce blocking by ad blockers and tracking protection."},
{t:"PCI-DSS",c:"data",d:"Card data security standard. Card details must never enter your capture; this is a scope question as well as a privacy one."},
{t:"Pseudonymisation",c:"data",d:"Replacing a direct identifier with a hashed or tokenised value, with the lookup held separately by the controller. The correct pattern for a gambling uid."},
{t:"Right to erasure",c:"data",d:"A player's right to have their data deleted. Executed against Fullstory through the server-side API; needs a runbook with a named owner."},
{t:"SCA / 3DS",c:"data",d:"Strong Customer Authentication and 3-D Secure. Mandatory in Europe for card payments; adds a step and a failure mode to every card deposit."},
{t:"Special category data",c:"data",d:"Sensitive data under GDPR with heightened protection. Responsible-gambling status is adjacent to health data and should be treated with the same caution."}
];

/* ---------- DRILL QUESTIONS ---------- */
window.QUIZ = [
{c:"product",q:"A casino client says the slot game area is blank in every replay. What is the correct explanation?",
 o:["Capture is misconfigured and needs re-installing","The game renders in canvas or a third-party iframe, which a DOM recorder cannot capture","Session sampling has excluded the game","The provider is blocking Fullstory deliberately"],a:1,
 w:"Fullstory records DOM structure and mutations, not pixels. Canvas, WebGL and cross-origin iframes have no DOM to record. Say this in the first meeting rather than letting it be discovered in a demo — then explain that you instrument the edges: launch, load outcome, time to playable and exit."},
{c:"product",q:"Which segment scope answers 'which players have never completed verification'?",
 o:["Session scope","User scope","Either — they give the same answer","Page scope"],a:1,
 w:"It is a property of the person across all time, so it is user scope. Session scope would only tell you which individual visits lacked the event, which is a different and much less useful question."},
{c:"product",q:"A client's top rage-click element is the sportsbook stake stepper. What do you do?",
 o:["Report it as the number one frustration finding","Suppress the signal on repeat-click controls and re-run the analysis","Recommend removing the stepper","Increase the rage-click threshold globally"],a:1,
 w:"Steppers, quick-stake chips and spin buttons generate legitimate repeat clicks. Suppress the signal on those elements before reporting anything, or your first frustration report will be laughed out of the room."},
{c:"product",q:"When does user-property overwriting cause a wrong conclusion?",
 o:["Never — properties are versioned","When a player's tier changes, every historical session shows the new tier","Only for anonymous users","Only with numeric properties"],a:1,
 w:"User properties are overwritten, not versioned. A player promoted to Platinum today appears Platinum in their Bronze-era sessions too. When the historical value matters, stamp it as an event or page property at the time it applied."},
{c:"product",q:"What is the correct first analysis on any newly instrumented account?",
 o:["Browse the most recent sessions","Build the full dashboard suite","Rank error clicks by sessions affected and quantify the conversion gap","Run a journey analysis from the homepage"],a:2,
 w:"Error clicks have the highest ratio of genuine, fixable, revenue-affecting defects of any signal. Top five signatures, sessions affected, downstream conversion gap. It is thirty minutes of work and the most reliable route to a credible first finding."},
{c:"product",q:"A sportsbook SPA shows every player as having one page view lasting forty minutes. What is wrong?",
 o:["Session timeout is misconfigured","Virtual page changes are not being signalled on route transitions","Sampling is active","Identity is not set"],a:1,
 w:"Single-page apps need an explicit page-change signal on each route transition, ideally hooked into the router centrally. Without it, funnels break, page metrics are meaningless and heatmaps blend screens together."},
{c:"product",q:"Which is the strongest evidence that a client has genuinely adopted the tool?",
 o:["Weekly active user count","Number of replays watched","Segments and dashboards the client created themselves","Seats assigned"],a:2,
 w:"Client-created objects are the truest adoption signal. If they only consume what you built, they have adopted you rather than the tool — and that ends at the next budget cycle. It also falls months before usage figures do, making it the best early warning."},
{c:"domain",q:"A client says 'we did £100m of handle last quarter'. What have they told you?",
 o:["Their revenue","The total amount wagered, which is not revenue","Their net gaming revenue","Their profit"],a:1,
 w:"Handle is total staked. GGR is handle minus payouts; NGR is GGR minus bonuses, duty, payment fees and affiliate commission. Always price opportunities in NGR or you will be corrected in the meeting."},
{c:"domain",q:"Why is first-deposit success rate typically well below returning-player success rate?",
 o:["New players deposit larger amounts","New cards, no saved method, higher issuer scrutiny and unfamiliar flow","The cashier is different for new players","It is a measurement artefact"],a:1,
 w:"Unsaved payment details, unfamiliar flow, higher issuer scrutiny on a first gambling transaction, and more chance of a typo. It is also the most expensive failure in the funnel because acquisition cost has already been spent."},
{c:"domain",q:"Which of these should you never build as a targeting segment?",
 o:["Players who abandoned the cashier","Players with a high loss velocity, for a promotional offer","Players who searched and found nothing","VIP-tier players seeing errors"],a:1,
 w:"Targeting by inferred vulnerability is a licence-condition issue for the operator and a reputational one for you. Decline, explain why, and put it in writing. RG-adjacent segments feed suppression lists, never inclusion lists."},
{c:"domain",q:"A KYC step causes a 30% drop. The client asks you to remove it. What is your answer?",
 o:["Remove it and measure the uplift","In Great Britain verification before deposit is a legal requirement — optimise its clarity and speed instead","Move it later in the flow","Make it optional for low-value players"],a:1,
 w:"Verification before deposit or play is a UKGC requirement. You optimise comprehension and speed — explaining why it is happening and how long it takes — never completion. Saying this unprompted is what earns a compliance officer's trust."},
{c:"domain",q:"What does a high price-change rejection rate in a sportsbook betslip usually indicate to a player?",
 o:["That the site is fast","That the operator is manipulating odds against them","That their stake was too high","That they are in a restricted market"],a:1,
 w:"Players experience it as bad faith even though it is normal trading mechanics. You cannot change the trading model, but you can change how the change is surfaced and how fast the player can respond — which keeps the trading team on side."},
{c:"domain",q:"Which population should always be analysed separately on a gambling account?",
 o:["Desktop users","VIP-tier players","Players using Chrome","Weekend players"],a:1,
 w:"VIPs are often around 1% of players producing 30–50% of NGR. Any aggregate analysis that includes them without segmentation is dominated by, or blind to, the population that matters most commercially."},
{c:"domain",q:"What is a wagering requirement?",
 o:["The minimum deposit to qualify for a bonus","How many times a bonus must be staked before it can be withdrawn","The maximum bet allowed","The time limit on a promotion"],a:1,
 w:"Typically expressed as '30x'. It is the single largest source of player confusion and complaint in the industry, and therefore a rich and safe area for comprehension-focused UX work."},
{c:"onboarding",q:"Which discovery question most determines whether your engagement produces change?",
 o:["What is your conversion rate?","Which analytics do you use?","Who has the authority to prioritise a fix once we find one?","What is your retention period?"],a:2,
 w:"Findings without an owner who can prioritise them become a library of interesting observations. If the honest answer is 'nobody', fix that before you fix anything on the website."},
{c:"onboarding",q:"When must the first quantified finding be delivered?",
 o:["Whenever the data is fully complete","By around week four","At the first quarterly review","After all training is finished"],a:1,
 w:"Clients judge the tool by whether it told them something they did not know, quickly. Hold an easy win in reserve from the first day of capture and deliver it as soon as the data is credible enough to defend."},
{c:"onboarding",q:"A white-label client wants deposit funnel analysis. What is your first move?",
 o:["Build the funnel and see what appears","Establish in writing which pages the client can deploy code to without the provider","Ask for more budget","Deploy via tag manager and hope it reaches the cashier"],a:1,
 w:"On white-label platforms the provider frequently owns the cashier and registration. Establish the deployment boundary in the first call, in writing, or you will be blamed for a limitation that was never yours."},
{c:"onboarding",q:"How should you train forty people across five teams?",
 o:["One comprehensive ninety-minute session for everyone","Role-based sessions built around a job each role already has","Written documentation only","Train the champions and let them cascade"],a:1,
 w:"Generic all-hands training is how adoption dies. Train by role, in the language of the role, against real questions from their own backlog, and follow with four weeks of office hours."},
{c:"onboarding",q:"Your funnel says 68%; the client's BI report says 61%. What do you do first?",
 o:["Prove your number is correct","Write both definitions down in full, side by side, and reconcile on one day's data","Adjust your funnel to match","Present both and let them choose"],a:1,
 w:"It is almost always a definitional difference — scope, window, bot exclusion, deduplication — not a factual one. Establish that both are correct for their definition, agree which answers the business question, and document the residual gap. Being trusted beats being right."},
{c:"onboarding",q:"What is the earliest reliable warning that an account is in trouble?",
 o:["Falling weekly active users","The client stops creating their own segments","A missed renewal conversation","Declining replay views"],a:1,
 w:"It happens months before usage figures fall and long before anyone mentions the renewal. Check it every month."},
{c:"compliance",q:"Which is the correct treatment for a displayed account balance?",
 o:["Capture it normally","Apply fs-mask","Apply fs-exclude","Send it as a user property"],a:1,
 w:"Mask it: you keep the layout and the interaction context but obfuscate the value. Exclusion would remove the element entirely and break the visual context of the replay, which you often need in order to understand the journey."},
{c:"compliance",q:"A client wants to add masking to a field that has been captured unmasked for three weeks. What must you tell them?",
 o:["The history will be cleaned automatically","Masking applies at capture time only — the historical data needs deletion or a retention purge","Masking is retroactive within 30 days","Nothing, it resolves itself"],a:1,
 w:"Masking is never retrospective. This is why you audit masking in staging and then again in production within 24 hours of go-live, and screenshot it for the compliance file."},
{c:"compliance",q:"What is acceptable to capture about responsible-gambling behaviour?",
 o:["The player's markers-of-harm risk score","That an RG tool was opened and what action was taken","The operator's internal vulnerability classification","Intervention history"],a:1,
 w:"Interaction data is legitimate and is exactly what the client needs to improve RG journeys. Diagnosis or risk classification is health-adjacent and should never enter a third-party analytics tool."},
{c:"compliance",q:"A compliance team needs to prove players saw a mandated message. What is credible evidence?",
 o:["The element exists in the page source","The element was visible in the viewport, evidenced per session","The message is in the design system","Support has not complained"],a:1,
 w:"DOM presence is not evidence of display. Viewport visibility, captured per session and dated, is what makes the evidence credible to an auditor — and explaining that distinction in your methodology note is what makes you credible too."},
{c:"compliance",q:"Which identifier should be sent as the Fullstory uid for a gambling client?",
 o:["The player's email address","The username","A salted server-side hash of the internal player ID","The account number shown on statements"],a:2,
 w:"Stable, joinable to the warehouse, pseudonymous, and reversible only by the client. Never the email — it is directly identifying, adds no analytical value, and creates a consent question nobody wants to answer."},
{c:"compliance",q:"A player withdraws consent. What are the two required actions?",
 o:["Stop capture only","Stop capture and delete already-captured data for that uid","Delete data only","Mark the user as opted out in the CRM"],a:1,
 w:"<code>FS('shutdown')</code> stops further capture; the server-side Users API delete handles data already held. The client needs a documented runbook with a named owner and an SLA — build it during onboarding."}
];
