/* Drill deck — appended to the base set in data-kpi.js.
   k: "mcq" (default) | "flaw" (what is wrong with this) | "next" (what do you ask next)
   code: optional monospace preamble shown above the options. */
window.QUIZ = (window.QUIZ || []).concat([

/* ---------------- PRODUCT ---------------- */
{c:"product",q:"A client's cashier is a cross-origin iframe served by their platform provider. What can you see?",
 o:["Everything, as long as the snippet is on the parent page","Nothing inside it — you instrument the entry and the returned outcome only","The DOM but not the interactions","Only network requests"],a:1,
 w:"A cross-origin iframe you do not control is opaque to capture. You instrument the boundary: every entry into the cashier and every outcome the parent page is told about. Establish this in discovery, because it defines what you can promise about deposit analysis."},
{c:"product",q:"Why does a session recorded three months ago sometimes replay with the wrong styling?",
 o:["Fullstory compresses old sessions","Playback fetches assets and styles from their live URLs, which may have since changed","Retention has degraded the data","The capture script version changed"],a:1,
 w:"Replay reconstructs the page using stylesheets and images fetched at the time you watch. Redeploy a stylesheet and old sessions drift. Fullstory documents this; know it before a client points at a replay and says the tool is broken."},
{c:"product",q:"Which of these is captured by default with no tagging at all?",
 o:["The value a player typed into the stake field","Which form field was engaged and for how long","The player's account balance from their wallet API","The outcome of a server-side deposit settlement"],a:1,
 w:"Form interaction — which field, focus order, time in field, whether it completed — is autocaptured. The typed values are private by default. Balance and settlement come from other systems and must be sent deliberately, and balance should be bucketed if sent at all."},
{c:"product",q:"You add fs-exclude to a container that holds the card fields AND the confirm button. What breaks?",
 o:["Nothing — exclusion only affects text","You lose the confirm click, so the deposit funnel breaks","The page stops rendering in replay","Masking rules elsewhere stop working"],a:1,
 w:"Events targeting excluded elements are ignored entirely. Exclusion is for the fields; the controls around them should be masked or left alone. This is the most common self-inflicted instrumentation wound in a cashier."},
{c:"product",q:"A masked region contains a button labelled 'Withdraw'. How do you find it in search?",
 o:["Search for the text 'Withdraw'","By CSS selector, or by a name you gave it with data-fs-element","It cannot be found at all","Unmask it temporarily"],a:1,
 w:"Masked elements keep their interaction events but their text is never collected, so text search cannot reach them. Name important elements before you mask around them — that is the practical reason element naming matters, beyond localisation."},
{c:"product",q:"What is the correct denominator for 'attempts per successful deposit'?",
 o:["All sessions","All cashier opens","Successful deposit outcomes","All players"],a:2,
 w:"Attempts divided by successes. Above about 1.5 means the cashier is exhausting people on the way to a result that eventually works — a failure a plain success rate hides completely."},
{c:"product",q:"Your client runs six brands in one Fullstory org. An analyst builds a deposit funnel and presents it. What is your first question?",
 o:["Which date range did you use?","Did you filter by brand?","Is it user or session scope?","Which device?"],a:1,
 w:"All four matter, but brand is the one that makes a single-org multi-brand number meaningless rather than merely imprecise. This is the discipline cost of the one-org pattern and it must be enforced through naming conventions from day one."},
{c:"product",q:"Fullstory supports an Umbrella structure. What problem does it solve?",
 o:["Joining behaviour to revenue","Managing several distinct accounts centrally, with cross-account user administration","Reducing session quota consumption","Masking data across brands"],a:1,
 w:"Umbrella Management gives a group-level manager Admin-equivalent access across multiple accounts. It is the pattern built for exactly the multi-brand gambling group you will be working with, and most clients do not know it exists — ask about it by name."},
{c:"product",q:"You need a rate — deposits succeeded over deposits attempted — as a charted metric. What do you build?",
 o:["Two segments and divide them mentally each week","A two-step funnel; the conversion figure is the rate","A distribution broken down by outcome","A duration metric"],a:1,
 w:"The metric builder will not divide two arbitrary segments. A two-step funnel is the rate primitive: step one is the denominator, step two the numerator. Once that clicks, most metric construction becomes mechanical."},
{c:"product",q:"Where should the authoritative deposit outcome come from?",
 o:["The browser, because that is what the player experienced","The server, via the Events API","Whichever fires first","The payment provider's dashboard"],a:1,
 w:"The browser only knows what the page displayed. Send the authoritative outcome server-side and keep the browser event as the player's view. Where the two disagree you have found something genuinely valuable — the player was told one thing and the system did another."},
{c:"product",q:"An operator asks you to raise their session sampling to save quota. Which surface must never be sampled?",
 o:["The marketing blog","The cashier and registration","The lobby","Help content"],a:1,
 w:"The whole point is that rare failures are the expensive ones, and sampling hides exactly those. Capture the money flows at 100%; sample content and marketing surfaces. If you must sample broadly, sample per user so journeys stay whole."},
{c:"product",q:"Which is the best first place to look for quota you can reclaim?",
 o:["Reduce retention","Sample the cashier","Exclude bots, uptime monitors and internal IP ranges","Turn off mobile capture"],a:2,
 w:"Worthless traffic is free quota and typically recovers 5–15% before you have to compromise anything analytical. Do it before you touch sampling and long before you touch retention."},
{c:"product",q:"What does 'private by default' actually mean on the web SDK?",
 o:["Nothing is captured until you opt in","Input values are not captured, but rendered page text is","The whole page is masked","Only logged-in users are captured"],a:1,
 w:"Values typed into inputs are not captured; text rendered on the page is, unless you mask or exclude it. That distinction is the whole privacy workstream — balances, names and bet histories are rendered text and need explicit treatment."},
{c:"product",q:"A gambling client's site already defines a global called FS. What do you do?",
 o:["Rename their global","Set _fs_namespace to something unique and use it in every downstream call","Load Fullstory later in the page","Nothing — collisions resolve automatically"],a:1,
 w:"Fullstory documents this exact case. Change the namespace, then make sure every trackEvent and setIdentity call uses the new one. Missing one is a silent failure that only shows up as an event that never appears."},

/* ---------------- BUILD PATTERNS ---------------- */
{c:"build",k:"flaw",q:"What is wrong with this segment definition?",
 code:"Segment — session scope\n  Deposit Outcome  outcome = failed\n  AND\n  Deposit Attempted\n\nPurpose: find players who retried after a failure",
 o:["It should be user scope","It has no ordering, so it also matches players who succeeded then deposited again","The property name is wrong","It needs a time window"],a:1,
 w:"Co-occurrence is not sequence. Without ordering you catch anyone whose session contains both events in any order. Use a sequence condition: failed outcome THEN another attempt. This is the single most common segment-building error."},
{c:"build",k:"flaw",q:"What is wrong with this metric?",
 code:"Saved-method adoption\n  Numerator    deposits where isSavedMethod = true\n  Denominator  all successful deposits\n  Window       last 30 days",
 o:["The window is too short","The denominator includes first deposits, where nothing could have been saved","It should be user scope","isSavedMethod is the wrong property"],a:1,
 w:"A wrong denominator, which is where most wrong numbers come from. First deposits cannot use a saved method, so including them permanently drags the figure down and hides the real trend. Restrict to returning players."},
{c:"build",k:"flaw",q:"What is wrong with this funnel?",
 o:["Nothing — this is correct","Registration and deposit rarely happen in one visit, so session scope will undercount badly","The steps are in the wrong order","It needs a device filter"],
 code:"Funnel — SESSION scope\n  1. Registration Completed\n  2. KYC Outcome = passed\n  3. Deposit Outcome = success\n  Window: same session",a:1,
 w:"Reg-to-FTD must be user scope with a multi-day window. Verification routinely interrupts the journey and the player returns hours or days later. Session scope turns a normal journey into an apparent catastrophe."},
{c:"build",k:"flaw",q:"An analyst reports the top rage-clicked element on a sportsbook. What should you say?",
 code:"Top rage-clicked elements, last 30 days\n  1. .stake-stepper-plus      184,220 sessions\n  2. .quick-stake-chip         96,410\n  3. .betslip-place-bet        12,880",
 o:["Escalate the stepper to engineering immediately","Suppress the signal on repeat-click controls and re-run — rows 1 and 2 are normal use","Remove the stepper from the UI","Report it as the headline finding"],a:1,
 w:"Steppers and quick-stake chips are designed to be clicked repeatedly. Until they are suppressed the frustration data is noise, and presenting it will cost you the room. Row 3 is the one worth looking at."},
{c:"build",k:"flaw",q:"What is wrong with this instrumentation?",
 code:"FS('trackEvent', {\n  name: 'Bet Placed',\n  properties: {\n    stake: 12.50,\n    playerName: 'J Smith',\n    odds: 3.75,\n    betId: 'b_8812f'\n  }\n});",
 o:["betId should not be sent","playerName must never be sent, and stake should be bucketed","odds should be a string","The event name is wrong"],a:1,
 w:"Two faults. playerName is directly identifying and has no analytical value — that is what the hashed uid is for. Raw stake creates unusable cardinality and belongs in the warehouse, joined on the betId you are correctly already sending."},
{c:"build",k:"mcq",q:"Which pattern builds 'median time to verification'?",
 o:["Funnel conversion","A duration metric from a numeric property on the completing event","Segment size over time","A property distribution"],a:1,
 w:"Capture secondsToOutcome as a property on KYC Outcome and take the median. Never derive durations from event timestamps after the fact, and always chart the 90th percentile beside the median — for KYC the manual tail is the entire story."},
{c:"build",q:"Why report the 90th percentile alongside the median for any duration metric?",
 o:["It is conventional","The median hides a struggling minority, and the tail is usually the finding","P90 is more accurate","To satisfy BI"],a:1,
 w:"A median of 110 seconds with a P90 of nine minutes means a large group is having a bad time and the median cannot see them. In gambling that tail is often a specific device class or a manual review path."},
{c:"build",q:"You rank lobby games by raw click count and recommend the top ten stay in row one. What have you actually measured?",
 o:["Game popularity","Position — you have re-measured the existing layout","Provider quality","Player intent"],a:1,
 w:"Clicks decay steeply by position, so raw counts mostly encode where things already are. Normalise against the positional decay curve and rank on the residual, or your recommendation is 'keep everything where it is'."},
{c:"build",q:"Which KPIs can Fullstory not produce on its own?",
 o:["Deposit success rate and betslip conversion","Hold percentage, NGR per active and wagering completion","Rage click rate and error click rate","Registration completion and KYC pass rate"],a:1,
 w:"Anything requiring settlement, wagering or revenue data needs a warehouse join. Your half is defining the behavioural cohort; the client's BI team returns the money. Overclaiming here loses technical stakeholders fast."},
{c:"build",q:"For a page-performance metric, which figure should you report?",
 o:["The mean","The median","The 75th percentile","The minimum"],a:2,
 w:"Web vitals are conventionally reported at the 75th percentile — the median flatters and the mean is distorted by outliers. Then split by device class, because mid-range Android is the real test, not the analyst's phone."},

/* ---------------- DOMAIN ---------------- */
{c:"domain",k:"next",q:"A Head of Digital says: 'Our deposit conversion is 87% and we're happy with it.' What do you ask next?",
 o:["What is your target?","87% of what — attempts, or cashier opens? And split by method and by first versus returning?","Which PSP do you use?","How long has it been 87%?"],a:1,
 w:"A blended figure hides everything. First deposits run well below returning, card runs well below wallets, and the denominator choice moves the number several points. Get to the split before you accept the headline."},
{c:"domain",k:"next",q:"A client says: 'KYC is fine, we pass 92% of players.' What do you ask next?",
 o:["Which vendor?","Is that first-attempt pass, or eventual pass — and what happens to the ones referred to manual review?","How long does it take?","What is the cost per check?"],a:1,
 w:"Clients quote eventual pass because it looks better. First-attempt pass predicts drop-off, and the referred population converts far worse than anyone expects. That gap is routinely the biggest loss in a GB funnel."},
{c:"domain",k:"next",q:"A commercial director says: 'This affiliate sends us 40,000 clicks a month and almost no depositors.' What do you ask next?",
 o:["Shall we stop paying them?","Before we call it fraud — what does their traffic do on site compared with a known-good source?","What is their commission model?","Which countries?"],a:1,
 w:"Engagement depth separates bot traffic, incentivised traffic and a landing-experience mismatch — three problems with three different answers. Show the behaviour and let the client draw the commercial conclusion; this report may be used to withhold payment."},
{c:"domain",k:"next",q:"A product owner says: 'Players keep complaining we change the odds when they try to bet.' What do you ask next?",
 o:["Can we stop doing that?","What is our rejection rate by magnitude and by in-play versus pre-match, and how long are people sitting in the betslip?","Is it a bug?","Which sports?"],a:1,
 w:"Price movement is legitimate trading, so the fix is never 'stop'. Rejection correlates with dwell time in the betslip, which is a UX problem you can solve without touching the trading model — and that framing keeps the trading team on your side."},
{c:"domain",q:"An operator's NGR is £40m and GGR is £58m. What is the £18m?",
 o:["Player winnings","Bonuses, gaming duty, payment fees and usually affiliate commission","Marketing spend","Operating costs"],a:1,
 w:"Payouts are already removed to get from handle to GGR. The step from GGR to NGR removes bonus cost, duty, payment processing and typically affiliate commission. NGR is the number to price opportunities in."},
{c:"domain",q:"Why is sportsbook revenue far more volatile than casino revenue?",
 o:["Sportsbook has more players","The operator is a counterparty to outcomes, so a single result can swing a month","Casino has better margins","Sportsbook has higher costs"],a:1,
 w:"Casino grinds out a fixed house edge over a huge number of small fast bets and is statistically predictable. A sportsbook can lose heavily when favourites win. It changes how the business thinks about risk and how it reads any week-on-week number."},
{c:"domain",q:"A casino client wants to improve 'game performance'. What is actually in scope for you?",
 o:["The slot mathematics and RTP","Finding, launching and loading the game, and what happens when it fails","The provider's server capacity","The bonus round design"],a:1,
 w:"Game maths is fixed by the supplier and certified by a test house. Your surface is discovery, launch, load time, failure handling and return-to-lobby — which is where the losses actually are anyway."},
{c:"domain",q:"What does a 35x wagering requirement on a £100 bonus mean?",
 o:["The player must deposit £3,500","£3,500 must be staked before bonus funds can be withdrawn","The bonus is worth £3,500","The player must play 35 times"],a:1,
 w:"Thirty-five times the bonus amount must be wagered. Whether it is calculated on bonus alone or deposit plus bonus varies by operator — which is precisely why it confuses players and why it is such fertile ground for comprehension work."},
{c:"domain",q:"Why does game weighting matter to a player, and why do so few understand it?",
 o:["It changes the RTP","It decides how much each game contributes to wagering, and it is almost never communicated clearly","It sets the maximum bet","It affects jackpot eligibility only"],a:1,
 w:"Slots often count 100% and table games 10% or 0%. A player clearing a bonus on blackjack may make almost no progress and have no idea. Instrument whether the weighting table is ever actually displayed."},
{c:"domain",q:"Roughly what share of NGR commonly comes from the top 1% of players at a gambling operator?",
 o:["Around 5%","Around 15%","Frequently 30–50%","Under 2%"],a:2,
 w:"Revenue concentration is extreme. Any analysis that does not segment VIPs separately is either dominated by them or blind to them, and any VIP-affecting defect is an emergency rather than a ticket."},
{c:"domain",q:"In Great Britain, when must age and identity verification happen?",
 o:["Within 72 hours of registration","Before the player can deposit or gamble","On first withdrawal","Only if flagged by risk"],a:1,
 w:"Verification sits inside the conversion funnel in GB, unlike markets where it can be deferred. That is why KYC abandonment is so often the largest single loss, and why it is a comprehension problem rather than a friction-removal problem."},
{c:"domain",q:"What is a PAM in an operator's stack?",
 o:["A payment processor","The Player Account Management platform — accounts, wallet, bonuses, compliance","A marketing automation tool","A provider aggregator"],a:1,
 w:"The system of record everything else plugs into. On a white-label deal the PAM belongs to the provider, which usually means the cashier and registration are not the client's code to tag."},
{c:"domain",q:"Which behaviour most reliably predicts lifetime value early?",
 o:["Session length on day one","Making a second deposit","Number of games launched","Bonus claimed"],a:1,
 w:"The second deposit is the strongest early signal in real-money gambling. Many operators track only the first. Handing them a second-deposit funnel and a time-to-second-deposit median is a genuinely valuable early deliverable."},
{c:"domain",q:"Why should you separate in-play from pre-match in every sportsbook analysis?",
 o:["They use different payment methods","In-play is time-critical, so friction has a completely different cost","Pre-match has more players","Regulators require it"],a:1,
 w:"A two-second delay pre-match is an annoyance; in-play it is a lost bet. Blending them produces a number that is wrong for both populations and actionable for neither."},

/* ---------------- ONBOARDING ---------------- */
{c:"onboarding",k:"next",q:"A client says: 'Yes, we can add tags to the site.' What do you ask next?",
 o:["Through GTM or directly?","Which pages specifically — including the cashier and registration — and do you need anyone else's permission?","How fast can you deploy?","Who approves it?"],a:1,
 w:"'We can add tags' very often means the marketing pages only. On a white-label deal the money surfaces belong to the provider. Get the deployment boundary in writing in the first call or you will be blamed for it in week six."},
{c:"onboarding",k:"next",q:"A sponsor says: 'We want to improve conversion.' What do you ask next?",
 o:["By how much?","Conversion of what, to what — and who owns that number today?","What is your budget?","Which page?"],a:1,
 w:"'Conversion' spans registration, verification, deposit, first play and second deposit, and they have different owners and different fixes. Naming the step and the owner converts a wish into a workstream."},
{c:"onboarding",q:"Your instrumentation spec lists event names and trigger conditions only. What happens?",
 o:["The developer implements it correctly","It comes back with wrong property names and types, and the rework lands in your week","It gets rejected","Nothing — names are enough"],a:1,
 w:"A spec must let a developer implement without asking you a single question: exact property names, types, example values, allowed enum values, and which KPI each feeds. Anything less guarantees a second pass."},
{c:"onboarding",q:"When should the privacy audit be repeated in production?",
 o:["Annually","Within 24 hours of go-live, then after every significant release","Only if compliance asks","Once, in staging"],a:1,
 w:"Masking rules that depend on selectors are broken silently by redesigns, and masking is never retrospective. The 24-hour production audit with screenshots is your evidence and your insurance."},
{c:"onboarding",q:"Which integration produces the fastest department-wide adoption?",
 o:["The warehouse join","Replay links attached automatically to support tickets","The experimentation platform","Slack alerts"],a:1,
 w:"Support agents feel the benefit on the first ticket and evangelise internally in a way analysts do not. Do it in week five, not week twelve, and take the cannot-reproduce baseline before you switch it on."},
{c:"onboarding",q:"What should you do before the first training session?",
 o:["Write documentation","Pre-build the segment, funnel and dashboard library","Collect feedback","Set up SSO"],a:1,
 w:"Nobody builds their first segment unprompted. Ship a complete, well-named library and teach people to modify rather than create. Then track client-created objects as the real adoption metric."},
{c:"onboarding",q:"A challenger brand's CEO is in every call and follow-through is thin. What is the right response?",
 o:["Escalate to get more resource","Ruthless minimum viable instrumentation, pre-build everything, defend a short fortnightly rhythm","Extend the timeline","Train more people"],a:1,
 w:"Speed is the whole proposition for a challenger. Registration, KYC, deposit, game launch — nothing else until those work. Assume they will not build their own objects and plan for it rather than being disappointed by it."},
{c:"onboarding",q:"A client's BI team is mature and sceptical. What do you do first?",
 o:["Present your findings to win them over","Involve them from week one and run the reconciliation exercise before anything goes external","Avoid them and work with product","Ask for their data model"],a:1,
 w:"A mature data team will challenge your numbers, and they should. Reconcile early, document the residual gap, and get both signatures. Being trusted is worth far more than being right."},
{c:"onboarding",q:"You have found a serious defect in week two but the data is only three days old. What do you do?",
 o:["Present it immediately","Hold until the sample is defensible, then present with the number and the caveat","Wait for the quarterly review","Mention it informally and move on"],a:1,
 w:"A finding in week four is close to mandatory, but a finding you cannot defend costs more than it earns. Size it properly, state the window, and present it as soon as it will survive a challenge — not before."},

/* ---------------- COMPLIANCE ---------------- */
{c:"compliance",k:"next",q:"A CRM manager asks for a segment of players 'showing signs of chasing losses' to send a reactivation offer. What do you say?",
 o:["Ask for the definition of chasing","No — targeting by inferred vulnerability is a licence-condition issue; I will put that in writing","Build it but anonymise it","Escalate to the sponsor"],a:1,
 w:"Decline, explain why, and record it. RG-adjacent segments feed suppression lists, never inclusion lists. Saying this clearly and early is what makes a compliance function trust you for the rest of the engagement."},
{c:"compliance",q:"Which of these may legitimately be captured?",
 o:["The operator's markers-of-harm score as a user property","That a deposit-limit screen was opened and a limit was set","A self-exclusion risk band","Intervention history"],a:1,
 w:"Interaction with a tool is UX data and is exactly what the client needs to improve RG journeys. Risk scores, bands and intervention history are diagnosis — health-adjacent, and they do not belong in a third-party analytics tool."},
{c:"compliance",q:"An auditor asks how you know players saw a mandated message. What is credible?",
 o:["The element is in the page template","Per-session evidence that it was visible in the viewport, with dated sample replays","Support has had no complaints","The design includes it"],a:1,
 w:"DOM presence proves nothing about display. Use an intersection observer to fire the event on actual visibility, keep dated samples, and put the distinction in your methodology note — that is what makes it stand up."},
{c:"compliance",q:"A client's account closure flow has seven steps; registration has three. What is your recommendation?",
 o:["Leave it — closure friction aids retention","Cut it to the minimum; optimise closure for speed, not retention","Add a retention offer at step four","Match it to registration at three steps"],a:1,
 w:"Regulators look at closure and self-exclusion flows specifically. Optimise for speed. A retention offer inserted into a closure journey is exactly the finding you do not want attached to your name."},
{c:"compliance",q:"Consent is withdrawn by a player. What are the two actions?",
 o:["Stop capture","Stop capture, and delete data already held for that uid via the server-side API","Delete data only","Flag the account"],a:1,
 w:"Shutdown stops further capture; the Users API delete handles history. The client needs a runbook with a named owner and an SLA — build it during onboarding, and make sure it is tested at least once while you are still there."},
{c:"compliance",q:"Which of these belongs in the exclusion list rather than the masking list?",
 o:["The displayed account balance","Source-of-funds documents uploaded during AML checks","The player's username in the header","Bet history amounts"],a:1,
 w:"Anything you must be able to swear was never transmitted gets excluded outright. Balances, names and histories are masked, because you still want the layout and the interaction context in replay."},
{c:"compliance",q:"A client operating in Ontario asks you to optimise their bonus banner placement. What is the complication?",
 o:["Bonuses are illegal there","Advertising inducements publicly is heavily restricted in Ontario, so most of that surface does not exist","Banners are blocked by regulation","Nothing — it works like the UK"],a:1,
 w:"Ontario's rules on advertising inducements remove most of the promotional surface you would normally optimise. Knowing this before the workshop stops you designing a programme around something the client cannot legally do."},
{c:"compliance",q:"What is the correct framing when a regulated journey shows a large drop-off?",
 o:["It is a conversion problem and should be fixed","Establish first whether the friction is mandated; if it is, optimise comprehension and speed, never completion","Escalate to compliance and stop work","Remove the step and measure"],a:1,
 w:"Ask before you optimise. A KYC hard stop, an affordability interruption or a deposit-limit prompt exists by law. Making it clearer and faster is legitimate and valuable; making more people pass through it is not."},
{c:"compliance",q:"Why does data residency come up on gambling accounts more than most?",
 o:["Gambling data is larger","Licence conditions in markets like the UK, Malta and Ontario can constrain where player data is stored","It is a Fullstory limitation","Players demand it"],a:1,
 w:"The operator will have a regulator-facing answer to 'where is player data held', and your configuration has to be consistent with it. Establish it in discovery, because it can force the account structure."},

/* ---------------- MIXED / JUDGEMENT ---------------- */
{c:"onboarding",q:"You quantify a defect at £310k of annualised NGR using an ARPU figure you looked up online. What is wrong?",
 o:["The figure is too high","You must use the client's own value figure from their finance team","NGR is the wrong unit","It should be a point estimate"],a:1,
 w:"The moment you use their number the finding becomes theirs to defend rather than yours to justify. An external figure invites an argument about the figure instead of a decision about the fix."},
{c:"onboarding",q:"How should you present the value of a correlational finding?",
 o:["A single confident number","A range, with the causal caveat stated before anyone else raises it","Qualitatively, with no number","Two scenarios, best and worst case"],a:1,
 w:"'Between £180k and £340k, depending on whether the effect is causal' is credible and gets a decision. A single confident number invites a challenge to the number, which is a conversation you cannot win and do not need."},
{c:"domain",q:"Why is withdrawal UX a retention investment rather than a cost centre?",
 o:["Withdrawals generate fees","It is the most emotionally charged journey and the biggest driver of complaints and negative reviews","It is cheap to fix","Regulators score it"],a:1,
 w:"Withdrawal problems escalate to regulators and review sites faster than anything else. Framing it as reputational risk management rather than support cost gets it prioritised far more quickly."},
{c:"product",q:"What is the honest description of what session replay adds next to GA4?",
 o:["It replaces GA4","GA4 tells them what changed; this tells them why","It is more accurate than GA4","It is a cheaper alternative"],a:1,
 w:"Never position it as an analytics replacement — you will lose to the incumbent and to the team that owns it. Complementary is both true and strategically correct."},
{c:"build",q:"You need 'cross-sell rate: sportsbook players who became casino players'. What counts as success?",
 o:["Clicking the cross-sell banner","Launching one casino game","A second casino session","Depositing again"],a:2,
 w:"A single curious visit is not a dual-product player. Counting the first launch makes a failing banner look successful; counting the second session tells you whether anything actually changed."},
{c:"product",q:"What is the fastest reliable first finding on a newly instrumented account?",
 o:["A journey analysis of the homepage","Top error clicks ranked by sessions affected, with the downstream conversion gap","A heatmap of the lobby","A full funnel suite"],a:1,
 w:"Error clicks have the highest ratio of genuine, fixable, revenue-affecting defects of any signal. Thirty minutes of work, and it is the exercise that most reliably produces a credible win inside two weeks."}
]);

/* --- experimentation methodology --- */
window.QUIZ = window.QUIZ.concat([
{c:"experiment",q:"A client wants to detect a 5% relative lift on a step with a 5% baseline conversion rate. Roughly what sample do they need per variant?",
 o:["About 3,000","About 30,000","About 120,000","About 500"],a:2,
 w:"Low baselines are brutally expensive. At a 5% baseline, a 5% relative MDE needs over 120,000 sessions per variant. The same relative lift on deposit success at a 90% baseline needs under 3,000. This is why gambling CRO concentrates on the cashier — dense traffic, high baseline, immediate money, and tests that actually conclude."},
{c:"experiment",q:"A 50/50 test is delivering a 48/52 split on 200,000 sessions. What do you do?",
 o:["Nothing — it is close enough","Stop: sample ratio mismatch invalidates the test, so find the cause first","Weight the results to correct for it","Extend the test until it balances"],a:1,
 w:"SRM means the randomisation or the measurement is broken — a redirect, a caching layer, an uneven bot filter, or the tag firing late on one variant. It invalidates the result entirely. Check it before you look at the outcome, every time, and never reason about a result from a test that failed it."},
{c:"experiment",q:"A variant wins strongly in week one and the lift decays in week two. What is the most likely explanation?",
 o:["The test is broken","A novelty effect among returning players","Seasonality","The sample was too small"],a:1,
 w:"Returning players react to change as change. Segment new versus returning and read them separately — if the lift holds for new users and decays for returning ones, it is novelty. The inverse pattern, a dip that recovers, is a primacy effect."},
{c:"experiment",q:"Which clause of a hypothesis do teams most often omit, and why does it matter most?",
 o:["The metric — without it you cannot measure","The mechanism and the falsification condition — without them a flat result gets rationalised into a partial win","The MDE — without it you cannot size the test","The owner — without one nothing ships"],a:1,
 w:"All four matter, but 'we will know we are wrong if…' is the one that gets skipped, and its absence is why flat tests produce no learning. A hypothesis with a real mechanism teaches you something even when it loses."},
{c:"experiment",q:"Why should a gambling test always run in whole weeks?",
 o:["Statistical convention","Traffic has a violent weekly shape — weekends, evenings, fixtures — so a part-week means the variants saw different populations","To give the client time to review","Because platforms bill weekly"],a:1,
 w:"Stop mid-week and your variant and control have seen different mixes of weekday and weekend traffic. Two full weeks is the practical minimum, and you check the fixture calendar before you start — a single major event can multiply traffic and change its composition completely."},
{c:"experiment",q:"A client proposes an A/B test on their VIP segment of 400 players. What is your answer?",
 o:["Run it with a longer duration","The population is far too small to reach useful precision — test on everyone and use replay to watch how VIPs experienced the variant","Lower the confidence threshold to 80%","Test on VIPs and a matched control"],a:1,
 w:"A few hundred players cannot support a test to any useful precision, whatever the duration. Say so before three weeks are spent on it. The honest alternative is quantitative evidence from the whole population plus qualitative evidence from watching VIP sessions."},
{c:"experiment",q:"Which of these may legitimately be A/B tested on a UK-licensed gambling site?",
 o:["Whether the deposit limit link appears in the footer or not at all","The wording of a decline message in the cashier","Whether age verification happens before or after first deposit","Whether the reality-check prompt is shown"],a:1,
 w:"Decline-message copy is ordinary UX. The other three all weaken or remove a regulatory control. Keep a standing exclusions list in the test plan template so the question is settled before someone proposes one in a workshop."},
{c:"experiment",q:"Your test is flat overall. Mobile won by 8%, desktop lost by 7%. What is the correct framing?",
 o:["Ship it to mobile only — the data supports it","Report it as exploratory: it generates the next hypothesis, it does not rescue this result","Call it a win with a caveat","Re-run the test on mobile with the same design"],a:1,
 w:"Post-hoc segmentation is exploratory, not confirmatory — slice enough ways and something looks significant by chance. Use it to design the next test, say 'this is exploratory' in writing, and do not let a flat result be relabelled a win."},
{c:"experiment",q:"When should an experiment-exposure event fire?",
 o:["On page load, so nobody is missed","At the moment the player is genuinely exposed to the tested element","When the session ends","When the player converts"],a:1,
 w:"Firing on load counts players who never scrolled to the tested element, which dilutes the effect and makes a real win look flat. Fire on genuine exposure — and send the variant as both a user property, so every segment filters by it, and an event, so you have exposure timing and a denominator for your own SRM check."}
]);
