/* The hands-on lab sandbox — a fake casino page with eight planted defects.
   Served to the learner as a downloadable single file. No dependencies. */
window.LAB_SANDBOX = [
'<!doctype html>',
'<html lang="en">',
'<head>',
'<meta charset="utf-8">',
'<meta name="viewport" content="width=device-width,initial-scale=1">',
'<title>Reel Harbour Casino — Fullstory Lab Sandbox</title>',
'',
'<!-- ================================================================= -->',
'<!--  PASTE YOUR FULLSTORY CAPTURE SNIPPET BETWEEN THESE TWO COMMENTS  -->',
'<!--  Settings > Data Capture > Fullstory Setup, then copy the snippet -->',
'',
'',
'<!--  END OF FULLSTORY SNIPPET                                        -->',
'<!-- ================================================================= -->',
'',
'<style>',
'  :root{--bg:#0f1418;--card:#182027;--line:#26323a;--ink:#e8eef2;--dim:#8fa0ad;',
'        --gold:#d4a24c;--green:#3fa06a;--red:#c4553f}',
'  *{box-sizing:border-box}',
'  body{margin:0;background:var(--bg);color:var(--ink);',
'       font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}',
'  header{display:flex;align-items:center;gap:16px;padding:12px 20px;',
'         border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--bg);z-index:5}',
'  .logo{font-weight:800;letter-spacing:.04em;color:var(--gold)}',
'  .bal{margin-left:auto;font-variant-numeric:tabular-nums;color:var(--dim)}',
'  .bal b{color:var(--ink)}',
'  main{max-width:980px;margin:0 auto;padding:22px 20px 80px}',
'  h2{font-size:18px;margin:30px 0 12px}',
'  button{font:inherit;cursor:pointer;border-radius:6px;border:1px solid var(--line);',
'         background:#202b33;color:var(--ink);padding:9px 15px}',
'  button:hover{border-color:var(--gold)}',
'  .primary{background:var(--gold);border-color:var(--gold);color:#1a1206;font-weight:700}',
'  input{font:inherit;width:100%;padding:9px 11px;border-radius:6px;',
'        border:1px solid var(--line);background:#121a20;color:var(--ink)}',
'  label{display:block;font-size:12px;color:var(--dim);margin:12px 0 4px}',
'  .panel{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:18px}',
'  .row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}',
'  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px}',
'  .tile{background:var(--card);border:1px solid var(--line);border-radius:9px;',
'        padding:14px;cursor:pointer;text-align:center}',
'  .tile:hover{border-color:var(--gold)}',
'  .tile .t{font-weight:600;font-size:14px}',
'  .tile .p{font-size:11px;color:var(--dim);margin-top:4px}',
'  /* DEFECT 1 — this looks exactly like a button and does nothing */',
'  .promo{background:linear-gradient(90deg,#3a2a10,#5a3f14);border:1px solid var(--gold);',
'         border-radius:9px;padding:16px 18px;margin:18px 0;cursor:pointer}',
'  .promo b{color:var(--gold)}',
'  .err{color:var(--red);font-size:13px;margin-top:8px;min-height:18px}',
'  .ok{color:var(--green)}',
'  dialog{background:var(--card);color:var(--ink);border:1px solid var(--line);',
'         border-radius:12px;padding:22px;width:min(440px,92vw)}',
'  dialog::backdrop{background:rgba(0,0,0,.6)}',
'  .stage{aspect-ratio:16/9;background:#070a0c;border:1px solid var(--line);',
'         border-radius:9px;display:grid;place-items:center;color:var(--dim);font-size:13px}',
'  footer{border-top:1px solid var(--line);margin-top:60px;padding:22px 20px;',
'         color:var(--dim);font-size:12px;text-align:center}',
'  footer a{color:var(--dim)}',
'  .steps{display:flex;gap:8px;margin-bottom:14px}',
'  .steps i{flex:1;height:3px;background:var(--line);border-radius:2px}',
'  .steps i.on{background:var(--gold)}',
'</style>',
'</head>',
'<body>',
'',
'<header>',
'  <span class="logo">REEL HARBOUR</span>',
'  <button id="nav-lobby">Lobby</button>',
'  <button id="nav-reg">Join</button>',
'  <button id="nav-cashier" class="primary">Deposit</button>',
'  <span class="bal">Balance <b class="fs-mask" id="bal">&pound;25.00</b></span>',
'</header>',
'',
'<main>',
'',
'  <!-- DEFECT 1: dead promotional banner -->',
'  <div class="promo" id="promo">',
'    <b>WELCOME OFFER</b> &mdash; 100% up to &pound;200 plus 50 spins.',
'    <span style="color:var(--dim)">35x wagering applies.</span>',
'  </div>',
'',
'  <h2>Lobby</h2>',
'  <div class="row" style="margin-bottom:12px">',
'    <input id="q" placeholder="Search games…" style="max-width:280px">',
'    <button id="searchbtn">Search</button>',
'    <span id="searchmsg" style="font-size:13px;color:var(--dim)"></span>',
'  </div>',
'  <div class="grid" id="grid"></div>',
'',
'  <h2>Game</h2>',
'  <div class="stage" id="stage">No game launched yet</div>',
'',
'</main>',
'',
'<!-- ---------------- registration ---------------- -->',
'<dialog id="reg">',
'  <div class="steps"><i class="on" id="s1"></i><i id="s2"></i><i id="s3"></i></div>',
'  <h3 style="margin:0 0 4px" id="regtitle">Create your account</h3>',
'  <div id="regbody"></div>',
'  <div class="err" id="regerr"></div>',
'  <div class="row" style="margin-top:16px">',
'    <button class="primary" id="regnext">Continue</button>',
'    <button id="regclose">Cancel</button>',
'  </div>',
'</dialog>',
'',
'<!-- ---------------- cashier ---------------- -->',
'<dialog id="cashier">',
'  <h3 style="margin:0 0 10px">Deposit</h3>',
'  <div class="row">',
'    <button class="amt">&pound;10</button><button class="amt">&pound;25</button>',
'    <button class="amt">&pound;50</button><button class="amt">&pound;100</button>',
'  </div>',
'  <label for="amt">Amount</label>',
'  <input id="amt" value="25" inputmode="decimal">',
'',
'  <!-- DEFECT 4: card details are NOT excluded. Fix this in exercise 2. -->',
'  <div id="cardblock">',
'    <label for="card">Card number</label>',
'    <input id="card" placeholder="4111 1111 1111 1111" autocomplete="off">',
'    <div class="row" style="margin-top:10px">',
'      <div style="flex:1"><label for="exp">Expiry</label><input id="exp" placeholder="12/29"></div>',
'      <div style="flex:1"><label for="cvv">CVV</label><input id="cvv" placeholder="123"></div>',
'    </div>',
'  </div>',
'',
'  <div class="err" id="casherr"></div>',
'  <div class="row" style="margin-top:16px">',
'    <!-- DEFECT 3: four second wait, no spinner, no disabled state -->',
'    <button class="primary" id="deposit">Deposit now</button>',
'    <button id="cashclose">Cancel</button>',
'  </div>',
'</dialog>',
'',
'<footer>',
'  Reel Harbour is a fictional brand built for training. No real money, no real games.',
'  <br>',
'  <!-- DEFECT 8: responsible gambling buried in the footer only -->',
'  <a href="#" id="rg">Responsible gambling</a> &middot;',
'  <a href="#">Terms</a> &middot; <a href="#">Privacy</a> &middot; 18+',
'</footer>',
'',
'<script>',
'(function(){',
'  var FS = window.FS || function(){};',
'',
'  /* ---------- helpers ---------- */',
'  function ev(name, props){ try{ FS("trackEvent", {name:name, properties:props||{}}); }catch(e){} }',
'  function bucket(n){ n=+n||0; return n<10?"0-9":n<25?"10-24":n<50?"25-49":n<100?"50-99":"100+"; }',
'  var $ = function(s){ return document.querySelector(s); };',
'',
'  /* ---------- lobby ---------- */',
'  var GAMES = [',
'    {id:"g1", t:"Harbour Gold",     p:"Pragmatic"},',
'    {id:"g2", t:"Neon Reels",       p:"Hacksaw"},',
'    {id:"g3", t:"Kraken Fortune",   p:"Relax"},',
'    {id:"g4", t:"Lucky Anchor",     p:"NetEnt"},',
'    {id:"g5", t:"Midnight Roulette",p:"Evolution"},',
'    /* DEFECT 2: this tile throws on click */',
'    {id:"g6", t:"Broken Bandit",    p:"Pragmatic", boom:true},',
'    /* DEFECT 7: present in the grid, missing from the search index */',
'    {id:"g7", t:"Tidewater Bonanza",p:"Relax", unsearchable:true},',
'    {id:"g8", t:"Crown & Compass",  p:"Play n GO"}',
'  ];',
'',
'  var grid = $("#grid");',
'  GAMES.forEach(function(g, i){',
'    var d = document.createElement("div");',
'    d.className = "tile";',
'    d.setAttribute("data-id", g.id);',
'    d.innerHTML = "<div class=\\"t\\">" + g.t + "</div><div class=\\"p\\">" + g.p + "</div>";',
'    d.addEventListener("click", function(){',
'      ev("Game Tile Clicked", {gameId:g.id, gameName:g.t, provider:g.p, lobbyPosition:i+1});',
'      launch(g);',
'    });',
'    grid.appendChild(d);',
'  });',
'',
'  function launch(g){',
'    ev("Game Launched", {gameId:g.id, provider:g.p, launchSource:"lobby", isDemo:false});',
'    var stage = $("#stage");',
'    stage.textContent = "Loading " + g.t + "…";',
'    setTimeout(function(){',
'      if (g.boom) {',
'        ev("Game Load Outcome", {outcome:"failed", provider:g.p, errorCode:"INIT_UNDEFINED"});',
'        /* uncaught on purpose — this is what an error click looks like */',
'        window.__missingGameEngine.init(g.id);',
'        return;',
'      }',
'      ev("Game Load Outcome", {outcome:"success", provider:g.p, secondsToLoad:1});',
'      stage.innerHTML = "<canvas width=\\"640\\" height=\\"360\\" " +',
'        "style=\\"width:100%;height:100%;background:#0b1013\\"></canvas>";',
'      var c = stage.querySelector("canvas").getContext("2d");',
'      c.fillStyle = "#d4a24c"; c.font = "20px system-ui";',
'      c.fillText(g.t + " — drawn in canvas, invisible to replay", 30, 180);',
'    }, 900);',
'  }',
'',
'  /* ---------- search (DEFECT 7) ---------- */',
'  function search(){',
'    var q = ($("#q").value || "").trim().toLowerCase();',
'    if (!q) return;',
'    var hits = GAMES.filter(function(g){',
'      return !g.unsearchable && g.t.toLowerCase().indexOf(q) > -1;',
'    });',
'    ev("Lobby Search", {queryLength:q.length, resultCount:hits.length,',
'                        hadZeroResults:hits.length===0, query:q});',
'    $("#searchmsg").textContent = hits.length',
'      ? hits.length + " result(s): " + hits.map(function(g){return g.t;}).join(", ")',
'      : "No games found.";',
'  }',
'  $("#searchbtn").addEventListener("click", search);',
'  $("#q").addEventListener("keydown", function(e){ if (e.key === "Enter") search(); });',
'',
'  /* ---------- DEFECT 1: the promo has no handler at all ---------- */',
'',
'  /* ---------- registration ---------- */',
'  var step = 1;',
'  var REG = {',
'    1: {title:"Create your account",',
'        html:"<label for=\\"em\\">Email</label><input id=\\"em\\" placeholder=\\"you@example.com\\">" +',
'             "<label for=\\"pw\\">Password</label><input id=\\"pw\\" type=\\"password\\">"},',
'    2: {title:"About you",',
'        html:"<label for=\\"nm\\">Full name</label><input id=\\"nm\\" placeholder=\\"Test Player\\">" +',
'             "<label for=\\"dob\\">Date of birth</label><input id=\\"dob\\" placeholder=\\"DD/MM/YYYY\\">" +',
'             "<label for=\\"pc\\">Postcode</label><input id=\\"pc\\" placeholder=\\"SW1A 1AA\\">"},',
'    3: {title:"Almost there",',
'        html:"<label><input type=\\"checkbox\\" id=\\"tc\\" style=\\"width:auto\\"> " +',
'             "I am 18+ and accept the terms</label>" +',
'             "<label><input type=\\"checkbox\\" id=\\"mk\\" style=\\"width:auto\\"> " +',
'             "Send me offers</label>"}',
'  };',
'  function drawReg(){',
'    $("#regtitle").textContent = REG[step].title;',
'    $("#regbody").innerHTML = REG[step].html;',
'    $("#regerr").textContent = "";',
'    $("#s1").className = step >= 1 ? "on" : "";',
'    $("#s2").className = step >= 2 ? "on" : "";',
'    $("#s3").className = step >= 3 ? "on" : "";',
'  }',
'  $("#nav-reg").addEventListener("click", function(){',
'    step = 1; drawReg(); $("#reg").showModal();',
'    ev("Registration Started", {entryPoint:"header", deviceType:',
'       (innerWidth<768?"mobile":"desktop")});',
'  });',
'  $("#regclose").addEventListener("click", function(){ $("#reg").close(); });',
'  $("#regnext").addEventListener("click", function(){',
'    /* DEFECT 5: password rules are revealed only now, never before */',
'    if (step === 1) {',
'      var pw = ($("#pw") && $("#pw").value) || "";',
'      if (pw.length < 10 || !/[0-9]/.test(pw) || !/[A-Z]/.test(pw)) {',
'        $("#regerr").textContent =',
'          "Password must be at least 10 characters and include a number and a capital letter.";',
'        ev("Registration Failed", {stepName:"credentials", fieldName:"password",',
'                                   failureReason:"password rules not met"});',
'        return;',
'      }',
'    }',
'    ev("Registration Step Completed", {stepNumber:step, stepName:REG[step].title});',
'    if (step === 3) {',
'      ev("Registration Completed", {stepCount:3,',
'          marketingOptIn: !!($("#mk") && $("#mk").checked)});',
'      $("#reg").close();',
'      alert("Account created. (Not really — this is a sandbox.)");',
'      return;',
'    }',
'    step++; drawReg();',
'  });',
'',
'  /* ---------- cashier ---------- */',
'  var attempts = 0;',
'  $("#nav-cashier").addEventListener("click", function(){',
'    attempts = 0;',
'    $("#casherr").textContent = "";',
'    $("#cashier").showModal();',
'    ev("Cashier Opened", {entryPoint:"header", isFirstDeposit:true});',
'  });',
'  $("#cashclose").addEventListener("click", function(){ $("#cashier").close(); });',
'  Array.prototype.forEach.call(document.querySelectorAll(".amt"), function(b){',
'    b.addEventListener("click", function(){',
'      $("#amt").value = b.textContent.replace(/[^0-9]/g, "");',
'    });',
'  });',
'',
'  $("#deposit").addEventListener("click", function(){',
'    attempts++;',
'    var amount = $("#amt").value;',
'    $("#casherr").textContent = "";',
'    ev("Deposit Attempted", {depositAmountBucket:bucket(amount), currency:"GBP",',
'                             paymentMethod:"card", attemptNumber:attempts});',
'    var t0 = Date.now();',
'    /* DEFECT 3: four seconds, no spinner, button stays enabled */',
'    setTimeout(function(){',
'      var secs = Math.round((Date.now() - t0) / 1000);',
'      /* DEFECT 6: one in three fails with a message that helps nobody */',
'      if (Math.random() < 0.34) {',
'        ev("Deposit Outcome", {outcome:"failed", declineReason:"DO_NOT_HONOR",',
'                               providerCode:"05", paymentMethod:"card",',
'                               secondsElapsed:secs, attemptNumber:attempts});',
'        $("#casherr").textContent = "We were unable to process your payment.";',
'        return;',
'      }',
'      ev("Deposit Outcome", {outcome:"success", paymentMethod:"card",',
'                             depositAmountBucket:bucket(amount),',
'                             secondsElapsed:secs, attemptNumber:attempts,',
'                             isFirstDeposit:true});',
'      var bal = document.getElementById("bal");',
'      bal.textContent = "£" + ((+amount || 0) + 25).toFixed(2);',
'      $("#casherr").innerHTML = "<span class=\\"ok\\">Deposit successful.</span>";',
'    }, 4000);',
'  });',
'',
'  /* ---------- responsible gambling (DEFECT 8) ---------- */',
'  $("#rg").addEventListener("click", function(e){',
'    e.preventDefault();',
'    ev("RG Tool Interaction", {toolType:"info", action:"opened", entryPoint:"footer"});',
'    alert("Deposit limits, time-outs and self-exclusion would live here.");',
'  });',
'',
'  $("#nav-lobby").addEventListener("click", function(){',
'    window.scrollTo({top:0, behavior:"smooth"});',
'  });',
'})();',
'<' + '/script>',
'</body>',
'</html>'
].join('\n');
